# BTVN buoi 10

# BAI 1: PHAN RA MA TRAN

Ma trận

\
A=
\begin{bmatrix}
1&0&1\\
0&1&1\\
1&0&1\\
0&1&1
\end{bmatrix}
\

In [1]:
import numpy as np

A= np.array([[1,0,1],[0,1,1],[1,0,1],[0,1,1]])
print("A=", A)

A= [[1 0 1]
 [0 1 1]
 [1 0 1]
 [0 1 1]]


## 1. Chứng minh các cột phụ thuộc tuyến tính

Gọi ba cột của A lần lượt là

\[
a1,a2,a3
\]

Ta có

\[
a3=a1+a2
\]

Do đó

\[
a1+a2-a3=0
\]

=> Các cột phụ thuộc tuyến tính.

Hai cột đầu độc lập nên

\[
{rank}(A)=2
\]

In [2]:
np.linalg.matrix_rank(A)

np.int64(2)

## 2. Tính \(A^TA\)

\
AT=
\begin{bmatrix}
1&0&1&0\\
0&1&0&1\\
1&1&1&1
\end{bmatrix}


Theo định nghĩa

\[
A^TA
\]

Ta tính được:
A^TA= 
\begin{bmatrix}
2&0&2\\
0&2&2\\
2&2&4
\end{bmatrix}



In [3]:
ATA = A.T @ A
ATA

array([[2, 0, 2],
       [0, 2, 2],
       [2, 2, 4]])

## 3. Tìm eigenvalues và eigenvectors

Giải


det(A^TA-\lambda I)=0.


Ta thu được

\[
\lambda=6,2,0.
\]

In [4]:
eigvals, eigvecs = np.linalg.eigh(ATA)

eigvals

array([1.99931645e-16, 2.00000000e+00, 6.00000000e+00])

## 4. Sắp xếp λ1 ≥ λ2 ≥ λ3.

In [5]:
idx = eigvals.argsort()[::-1]

eigvals = eigvals[idx]
eigvecs = eigvecs[:, idx]

eigvals
eigvecs

array([[-4.08248290e-01, -7.07106781e-01, -5.77350269e-01],
       [-4.08248290e-01,  7.07106781e-01, -5.77350269e-01],
       [-8.16496581e-01, -1.11022302e-16,  5.77350269e-01]])

## 5.Tính các singular values σ
Theo định nghĩa


sigma_i=sqrt{lambda_i}

=> sigma_1= sqrt{6}

=> sigma_2= sqrt{2}
 
=> sigma_3= sqrt{0}

In [6]:
sigma = np.sqrt(np.maximum(eigvals,0))
sigma

array([2.44948974e+00, 1.41421356e+00, 1.41397187e-08])

## Câu 6. Xác định các right singular vectors

Theo lý thuyết SVD, các right singular vectors của ma trận \(A\) chính là các eigenvectors trực chuẩn của ma trận \(A^TA\), ứng với các eigenvalues đã sắp xếp theo thứ tự giảm dần.

Từ Câu 4, ta có

\[
lambda_1=6,
lambda_2=2,
lambda_3=0.
\]

Do đó các right singular vectors là

\
v_1=
\begin{bmatrix}
1\\
1\\
2
\end{bmatrix},
v_2=
\begin{bmatrix}
-1\\
1\\
0
\end{bmatrix},
v_3=
\begin{bmatrix}
1\\
1\\
-1
\end{bmatrix}.


Ghép các vector này thành ma trận

\[
V=
\begin{bmatrix}
\frac1{\sqrt6} & -\frac1{\sqrt2} & \frac1{\sqrt3}\\
\frac1{\sqrt6} & \frac1{\sqrt2} & \frac1{\sqrt3}\\
\frac2{\sqrt6} & 0 & -\frac1{\sqrt3}
\end{bmatrix}.
\]

## Câu 7 
Theo công thức

u_i={A*v_i}/{sigma_i}

với các singular value khác 0.

In [7]:
U = []

for i in range(2):
    ui = A @ eigvecs[:,i] / sigma[i]
    U.append(ui)

U = np.column_stack(U)
U

array([[-0.5, -0.5],
       [-0.5,  0.5],
       [-0.5, -0.5],
       [-0.5,  0.5]])

## Câu 8
Do rank(A)=2 nên chỉ có hai singular value khác 0.

Vì vậy chỉ xác định được hai vector \(u_1,u_2\).

Để tạo Full SVD cần bổ sung thêm hai vector trực chuẩn sao cho


U^T U=I.


Ở đây chọn

\[
u_3=
...

u_4=
...
\]

In [8]:
u3 = np.array([1,0,-1,0],dtype=float)
u3 /= np.linalg.norm(u3)

u4 = np.array([0,1,0,-1],dtype=float)
u4 /= np.linalg.norm(u4)

U_full = np.column_stack([U,u3,u4])

U_full

array([[-0.5       , -0.5       ,  0.70710678,  0.        ],
       [-0.5       ,  0.5       ,  0.        ,  0.70710678],
       [-0.5       , -0.5       , -0.70710678,  0.        ],
       [-0.5       ,  0.5       ,  0.        , -0.70710678]])

## Câu 9

In [9]:
Sigma = np.zeros((4,3))
Sigma[0,0]=sigma[0]
Sigma[1,1]=sigma[1]

V = eigvecs

Sigma

array([[2.44948974, 0.        , 0.        ],
       [0.        , 1.41421356, 0.        ],
       [0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        ]])

## Câu 10 


In [10]:
Ur = U
Sr = np.diag(sigma[:2])
Vr = V[:,:2]

Ur.shape, Sr.shape, Vr.shape

((4, 2), (2, 2), (3, 2))

## Câu 11: Kiểm tra
U^TU=I,
V^TV=I,
U Sigma V^T=A

In [11]:
np.allclose(U_full.T @ U_full, np.eye(4))

True

In [12]:
np.allclose(V.T @ V, np.eye(3))

True

In [13]:
np.allclose(U_full @ Sigma @ V.T, A)

True

## Câu 12:

1. Vì sao có một singular value bằng 0?

Do ma trận A có rank(A)=2<3, nên chỉ có 2 singular value khác 0. Vì vậy singular value còn lại bằng 0.

2. Singular vector ứng với singular value bằng 0 liên hệ thế nào với Null Space của A?

Singular vector ứng với singular value bằng 0 thuộc Null Space của A, vì khi σ=0 thì Av=0. Trong bài này, v3 là một vector cơ sở của Null(A).

3. Vì sao Reduced SVD vẫn tái tạo chính xác A?

Reduced SVD chỉ giữ các singular value khác 0. Thành phần ứng với σ=0 bằng ma trận 0 nên không đóng góp vào A. Do đó, Reduced SVD vẫn tái tạo chính xác ma trận A.

# Bai 2. Chọn k cho Truncated SVD bằng tỷ lệ năng lượng

## Câu 1: Xác định hạng K của ma trận 
Theo định lý của SVD, số singular values khác 0 chính bằng hạng của ma trận. Vì cả 4 singular values đều khác 0 nên ma trận có hạng bằng 4.

## Câu 2: Tính tổng năng lượng 
E= σ1^2 + σ2^2 + σ3^2 + σ4^2
 = 12^2 + 5^2  + 3^2  + 1^2
 = 179



## Câu 3: 
Tổng năng lượng của ma trận là

\[
E=12^2+5^2+3^2+1^2=179.
\]

Do đó:

\[
R(1)={144}/{179}=80.45%
\]

\[
R(2)={169}/{179}=94.41%
\]

\[
R(3)={178}/{179}=99.44%
\]

\[
R(4)={179}/{179}=100%.
\]

## Câu 4:
| k | Năng lượng giữ lại | Tỷ lệ (k)|
|:---:|:---:|:---:|
| 1 | 144 | 80.45%|
| 2 | 169 | 94.41%|
| 3 | 178 | 99.44%|
| 4 | 179 | 100%|



## Câu 5:
| Năng lượng giữ lại ít nhất | k |
|:---:|:---:|
| 80% | 0.99 |
| 90% | 1.684 |
| 95% | 2.11 |
| 98% | 2.71 |

## Câu 6:



\|X-X_k\|_F=sqrt{\sum_{i=k+1}^{4}\sigma_i^2}


Với các singular values:


\sigma_1=12,
\sigma_2=5,
\sigma_3=3,
\sigma_4=1.


Ta có bảng sau:

| \(k\) | Công thức | Giá trị |
|:---:|:---|:---:|
| 1 | sqrt{5^2+3^2+1^2} | sqrt{35}|
| 2 | sqrt{3^2+1^2} | sqrt{10} |
| 3 | sqrt{1^2} | 1 |

## Câu 7
| k | R(k) | Abs(X-Xk)F |
|:---:|:---:|:---:|
|1| 80.45% | sqrt{35}|
|2|94.41% |sqrt{10} |
|3|99.44% | 1|

## Câu 8
Giả sử σ4 chủ yếu biểu diễn nhiễu. Ta sẽ chọn k bằng 3 để giữ lại được hầu hết (99.44%) những thông tin quan trọng và loại bỏ được đi nhiễu với sai số là 1.

## Câu 9
### 1. Vì sao singular values phải được sắp xếp giảm dần?
Singular values được sắp xếp theo thứ tự giảm dần để các thành phần quan trọng nhất của dữ liệu xuất hiện trước. Điều này giúp dễ dàng lựa chọn số chiều k và xây dựng xấp xỉ tốt nhất của ma trận.
### 2. Giữ càng nhiều singular values có phải lúc nào cũng tốt hơn không?
Không. Giữ quá nhiều singular values có thể giữ lại cả nhiễu, làm tăng kích thước dữ liệu và giảm hiệu quả nén. Mục tiêu là giữ đủ thông tin cần thiết nhưng loại bỏ các thành phần ít quan trọng.
### 3. Sự đánh đổi giữa tỷ lệ năng lượng và mức độ nén dữ liệu là gì?
- Chọn k lớn: giữ được nhiều năng lượng hơn, sai số nhỏ hơn nhưng khả năng nén kém.
- Chọn k nhỏ: dữ liệu được nén tốt hơn nhưng mất nhiều thông tin hơn và sai số tăng.